export const payrollCopy = {
  ru: {
    heading: 'Ведомость кассиров', month: 'Месяц', city: 'Город', point: 'Точка',
    allCities: 'Все города', allPoints: 'Все точки', chooseCity: 'Сначала выберите город',
    unassignedPoint: 'Точка не указана',
    search: 'Найти кассира', cashier: 'Кассир', registrations: 'Регистрации',
    accrued: 'Начислено', paid: 'Выплачено', outstanding: 'К выплате', archive: 'В архиве',
    markPaid: 'Отметить выплату', confirm: 'Подтвердить выплату', cancel: 'Отмена',
    paymentNote: 'Отметка для учёта. Деньги не переводятся.',
    history: 'История выплат', actor: 'Отметил', recorded: 'Выплата отмечена',
    refresh: 'Обновить ведомость', export: 'Скачать Excel', exporting: 'Готовим Excel…',
    loading: 'Загружаем ведомость…', loadError: 'Не удалось загрузить ведомость',
    empty: 'Начислений за этот месяц нет', retry: 'Повторить',
    invalidMonth: 'Выберите месяц', changed: 'Данные изменились. Обновите ведомость и подтвердите новую сумму.',
    refreshData: 'Обновить данные', paymentError: 'Не удалось отметить выплату. Повторите попытку.',
    exportError: 'Не удалось скачать Excel', unknownActor: 'Администратор',
  },
  kk: {
    heading: 'Кассирлер ведомосі', month: 'Ай', city: 'Қала', point: 'Нүкте',
    allCities: 'Барлық қалалар', allPoints: 'Барлық нүктелер', chooseCity: 'Алдымен қаланы таңдаңыз',
    unassignedPoint: 'Нүкте көрсетілмеген',
    search: 'Кассирді табу', cashier: 'Кассир', registrations: 'Тіркелулер',
    accrued: 'Есептелді', paid: 'Төленді', outstanding: 'Төлеуге', archive: 'Мұрағатта',
    markPaid: 'Төлемді белгілеу', confirm: 'Төлемді растау', cancel: 'Бас тарту',
    paymentNote: 'Бұл — есепке алу белгісі. Ақша аударылмайды.',
    history: 'Төлем тарихы', actor: 'Белгілеген', recorded: 'Төлем белгіленді',
    refresh: 'Ведомості жаңарту', export: 'Excel жүктеу', exporting: 'Excel дайындалуда…',
    loading: 'Ведомость жүктелуде…', loadError: 'Ведомості жүктеу мүмкін болмады',
    empty: 'Бұл айда есептеулер жоқ', retry: 'Қайталау',
    invalidMonth: 'Айды таңдаңыз', changed: 'Деректер өзгерді. Ведомості жаңартып, жаңа соманы растаңыз.',
    refreshData: 'Деректерді жаңарту', paymentError: 'Төлемді белгілеу мүмкін болмады. Қайталап көріңіз.',
    exportError: 'Excel жүктеу мүмкін болмады', unknownActor: 'Әкімші',
  },
};
