export type Location = { id: string; name: string; city: string; active: boolean };
export type Partner = { id: string; name: string };
export type Terms = {
  branch_id: string;
  partner_id: string | null;
  commission_bps: number;
  bonus_compensation_bps: number;
  delivery_recipient: string;
  effective_at: string;
};
export type Config = { locations: Location[]; partners: Partner[]; terms: Terms[] };
export type BranchReport = {
  branch_id: string | null;
  name: string;
  city: string;
  orders: number;
  customers: number;
  paid_orders: number;
  completed_orders: number;
  cancelled_orders: number;
  refunded_orders: number;
  cash: number;
  refunds: number;
  net_cash: number;
  bonuses: number;
  delivery: number;
  discounts: number;
  commission: number;
  acquiring_fee: number;
  unverified: number;
};
export type Balance = {
  branch_id: string;
  partner_id: string;
  branch: string;
  partner: string;
  accrued: number;
  paid_out: number;
  balance: number;
  blocked: number;
};
export type OrderFinance = {
  order_id: string;
  order_number: number;
  ordered_at: string;
  branch: string;
  partner: string | null;
  status: string;
  fulfillment_status: string;
  cash_amount: number;
  cash_refunded: number;
  cash_net: number;
  bonus_net: number;
  delivery_net: number;
  discount_amount: number;
  platform_commission: number;
  bonus_compensation: number;
  acquiring_fee: number | null;
  payment_recipient: string;
  reconciled: boolean | null;
  current_signature: string;
  entitlement: number;
  paid_out: number;
  branch_changed: boolean;
  bank_reference: string | null;
};
export type Payout = {
  id: string;
  partner: string;
  branch: string;
  amount: number;
  bank_reference: string;
  paid_at: string;
};
export type Report = {
  canManage: boolean;
  branches: BranchReport[];
  balances: Balance[];
  orders: OrderFinance[];
  payouts: Payout[];
  totalOrders: number;
};
