<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>Resto.Front.Api.IikoBonusPlugin</AssemblyName>
    <RootNamespace>Resto.Front.Api.IikoBonusPlugin</RootNamespace>
    <Platforms>AnyCPU</Platforms>
    <Version>1.1.0</Version>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IikoFrontApiVersion>9.5.6059</IikoFrontApiVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Resto.Front.Api.V9" Version="$(IikoFrontApiVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Manifest.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resto.Front.Api.IikoBonusPlugin.dll.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
