#!/usr/bin/env bash
set -Eeuo pipefail

domain='bulka.com.kz'
nginx_conf='/etc/nginx/conf.d/bulka-cloudflare-origin.conf'
site_conf='/etc/nginx/sites-available/iiko-bonus'
timestamp=$(date -u +'%Y%m%dT%H%M%SZ')
backup_dir="/var/backups/bulka-cloudflare-${timestamp}"
ipv4_file=$(mktemp)
ipv6_file=$(mktemp)

cleanup() {
  rm -f -- "$ipv4_file" "$ipv6_file"
}
trap cleanup EXIT

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo 'Run this script through sudo.' >&2
  exit 1
fi
if [[ ${CONFIRM_CLOUDFLARE_ACTIVE:-} != "$domain" ]]; then
  echo "Set CONFIRM_CLOUDFLARE_ACTIVE=$domain only after the proxied zone is active." >&2
  exit 1
fi
test -f "$site_conf"

headers=$(curl -fsSI "https://${domain}/healthz")
printf '%s\n' "$headers" | grep -qi '^cf-ray:'
resolved_addresses=$(getent ahostsv4 "$domain" | awk '{print $1}' | sort -u)
if printf '%s\n' "$resolved_addresses" | grep -qx '185.113.132.73'; then
  echo 'Public DNS still exposes the origin address. Origin lockdown was not applied.' >&2
  exit 1
fi

curl -fsS 'https://www.cloudflare.com/ips-v4' -o "$ipv4_file"
curl -fsS 'https://www.cloudflare.com/ips-v6' -o "$ipv6_file"

# Cloudflare currently publishes exactly 15 IPv4 and 7 IPv6 ranges. Validate
# every nonblank line semantically before any Nginx file is touched. Rewriting
# the temporary files to canonical CIDR text also prevents unvalidated input
# from being interpolated into the generated configuration.
python3 - "$ipv4_file" "$ipv6_file" <<'PY'
import ipaddress
import sys
from pathlib import Path


def validate(filename: str, version: int, expected_count: int) -> None:
    path = Path(filename)
    raw_networks = [
        line.strip()
        for line in path.read_text(encoding="ascii").splitlines()
        if line.strip()
    ]
    if len(raw_networks) != expected_count:
        raise SystemExit(
            f"Cloudflare IPv{version} list contains {len(raw_networks)} ranges; "
            f"expected {expected_count}"
        )

    networks = []
    for raw_network in raw_networks:
        try:
            network = ipaddress.ip_network(raw_network, strict=True)
        except ValueError as error:
            raise SystemExit(f"Invalid Cloudflare IPv{version} range") from error
        if network.version != version:
            raise SystemExit(f"Unexpected address family in Cloudflare IPv{version} list")
        networks.append(str(network))

    if len(set(networks)) != expected_count:
        raise SystemExit(f"Cloudflare IPv{version} list contains duplicate ranges")
    path.write_text("\n".join(networks) + "\n", encoding="ascii")


validate(sys.argv[1], 4, 15)
validate(sys.argv[2], 6, 7)
PY

install -d -m 0700 "$backup_dir"
cp -a "$site_conf" "$backup_dir/iiko-bonus"
if [[ -f "$nginx_conf" ]]; then
  cp -a "$nginx_conf" "$backup_dir/bulka-cloudflare-origin.conf"
fi

rollback() {
  local exit_code=$?
  trap - ERR
  cp -a "$backup_dir/iiko-bonus" "$site_conf"
  if [[ -f "$backup_dir/bulka-cloudflare-origin.conf" ]]; then
    cp -a "$backup_dir/bulka-cloudflare-origin.conf" "$nginx_conf"
  else
    rm -f -- "$nginx_conf"
  fi
  nginx -t && systemctl reload nginx || true
  exit "$exit_code"
}
trap rollback ERR

{
  printf '# Generated by prepare-cloudflare-origin.sh at %s\n' "$timestamp"
  while read -r network; do
    [[ -n $network ]] && printf 'set_real_ip_from %s;\n' "$network"
  done <"$ipv4_file"
  while read -r network; do
    [[ -n $network ]] && printf 'set_real_ip_from %s;\n' "$network"
  done <"$ipv6_file"
  printf 'real_ip_header CF-Connecting-IP;\n'
  printf 'real_ip_recursive on;\n'
} >"$nginx_conf"

python3 - "$site_conf" "$ipv4_file" "$ipv6_file" <<'PY'
import re
import sys
from pathlib import Path

site_path = Path(sys.argv[1])
ranges = []
for filename in sys.argv[2:]:
    ranges.extend(
        line.strip()
        for line in Path(filename).read_text(encoding="utf-8").splitlines()
        if line.strip()
    )

text = site_path.read_text(encoding="utf-8")
begin = "        # BULKA_CLOUDFLARE_ALLOWLIST_BEGIN"
end = "        # BULKA_CLOUDFLARE_ALLOWLIST_END"
block = "\n".join(
    [begin, *[f"        allow {network};" for network in ranges], "        deny all;", end]
)
pattern = re.compile(
    rf"\n[ \t]*{re.escape(begin.strip())}.*?{re.escape(end.strip())}\n",
    re.DOTALL,
)
text = pattern.sub("\n", text)
needle = "    location / {\n"
if text.count(needle) != 1:
    raise SystemExit("Could not identify the production Nginx location block")
text = text.replace(needle, needle + block + "\n", 1)
site_path.write_text(text, encoding="utf-8")
PY

nginx -t
systemctl reload nginx
systemctl is-active --quiet nginx
curl -fsS "https://${domain}/healthz" >/dev/null
direct_status=$(curl -sk -o /dev/null -w '%{http_code}' \
  --resolve "${domain}:443:185.113.132.73" "https://${domain}/healthz")
if [[ $direct_status != '403' ]]; then
  echo "Direct origin request returned ${direct_status}; expected 403." >&2
  # A plain `exit` bypasses the ERR trap. This failing command deliberately
  # enters rollback so the previous Nginx configuration is restored.
  false
fi

trap - ERR
echo 'Cloudflare origin allowlist is active.'
echo "Backup: $backup_dir"
