const labels: Record<string, [string, string, string]> = {
  branches: ['По филиалам', 'Филиалдар бойынша', 'By branch'],
  products: ['По товарам', 'Тауарлар бойынша', 'By product'],
  documents: ['Документы', 'Құжаттар', 'Documents'],
  reasons: ['Статьи и причины', 'Баптар мен себептер', 'Accounts and reasons'],
  trend: ['Динамика по дням', 'Күндер бойынша', 'Daily trend'],
  discounts: ['Скидки', 'Жеңілдіктер', 'Discounts'],
  returns: ['Возвраты', 'Қайтарулар', 'Returns'],
  assortment: ['Ассортимент', 'Ассортимент', 'Assortment'],
  cost: ['Стоимость списаний', 'Есептен шығару құны', 'Write-off cost'],
  revenue: ['Выручка', 'Түсім', 'Revenue'],
  share: ['От выручки', 'Түсімнен', 'Share of revenue'],
  change: ['К прошлому периоду', 'Алдыңғы кезеңге', 'Vs previous period'],
  discount: ['Сумма скидок', 'Жеңілдіктер сомасы', 'Discount amount'],
  discountChecks: ['Чеков со скидкой', 'Жеңілдігі бар чектер', 'Discounted checks'],
  returnChecks: ['Чеков возврата', 'Қайтару чектері', 'Return checks'],
  flagged: ['Для проверки', 'Тексеру қажет', 'To review'],
  productsCount: ['Товаров × филиалов', 'Тауарлар × филиалдар', 'Products × branches'],
  increase: ['Проверить увеличение', 'Көбейтуді тексеру', 'Review an increase'],
  reduce: ['Пересмотреть выпечку', 'Пісіруді қайта қарау', 'Review production'],
  Department: ['Филиал', 'Филиал', 'Branch'],
  'Product.Name': ['Товар', 'Тауар', 'Product'],
  'Product.MeasureUnit': ['Единица', 'Өлшем', 'Unit'],
  WriteoffCost: ['Списано, ₸', 'Шығарылды, ₸', 'Write-off cost, ₸'],
  WriteoffQuantity: ['Списано, ед.', 'Шығарылған саны', 'Written off, units'],
  Revenue: ['Выручка, ₸', 'Түсім, ₸', 'Revenue, ₸'],
  WriteoffShare: ['Списания / выручка, %', 'Шығару / түсім, %', 'Write-offs / revenue, %'],
  DocumentCount: ['Документов', 'Құжат саны', 'Documents'],
  Reason: ['Статья списания', 'Есептен шығару бабы', 'Write-off account'],
  Comment: ['Комментарий / причина', 'Пікір / себеп', 'Comment / reason'],
  Day: ['Дата', 'Күні', 'Date'],
  Store: ['Склад', 'Қойма', 'Warehouse'],
  Document: ['Документ', 'Құжат', 'Document'],
  Cashier: ['Кассир', 'Кассир', 'Cashier'],
  AuthUser: ['Авторизовал в iiko', 'iiko-да рұқсат берген', 'Authorized in iiko'],
  OrderNum: ['Чек №', 'Чек №', 'Check #'],
  SourceOrderNum: ['Исходный чек', 'Бастапқы чек', 'Original check'],
  CloseTime: ['Время', 'Уақыты', 'Time'],
  DiscountName: ['Скидка', 'Жеңілдік', 'Discount'],
  DiscountSum: ['Скидка, ₸', 'Жеңілдік, ₸', 'Discount, ₸'],
  DiscountRate: ['Скидка на позиции, %', 'Позицияларға жеңілдік, %', 'Discount on items, %'],
  ReturnSum: ['Возврат, ₸', 'Қайтару, ₸', 'Refund, ₸'],
  Flags: ['Сигналы проверки', 'Тексеру белгілері', 'Review signals'],
  Sold: ['Продано', 'Сатылды', 'Sold'],
  PreviousSold: ['Ранее', 'Бұрын', 'Previously'],
  Daily: ['Продаж / день', 'Сату / күн', 'Sales / day'],
  Growth: ['Динамика, %', 'Өзгеріс, %', 'Change, %'],
  LossRate: ['Списания в движении, %', 'Қозғалыстағы шығару, %', 'Write-offs in movement, %'],
  Advice: ['Рекомендация', 'Ұсыныс', 'Suggestion'],
  Pace: ['Спрос', 'Сұраныс', 'Demand'],
  SuggestedDaily: ['Ориентир / день', 'Бағдар / күн', 'Daily reference'],
  high_discount: ['Высокая скидка', 'Жоғары жеңілдік', 'High discount'],
  large_return: ['Крупный возврат', 'Ірі қайтару', 'Large refund'],
  repeat_returns: ['3+ возврата за день', 'Күніне 3+ қайтару', '3+ refunds in a day'],
  review_increase: ['Проверить увеличение', 'Көбейтуді тексеру', 'Consider increasing'],
  reduce_batch: ['Проверить размер партии', 'Партия көлемін тексеру', 'Review batch size'],
  review_decline: [
    'Спрос снизился — проверить план',
    'Сұраныс төмендеді — жоспарды тексеру',
    'Demand fell — review plan',
  ],
  review_no_sales: [
    'Нет продаж — проверить наличие',
    'Сату жоқ — қорды тексеру',
    'No sales — check availability',
  ],
  keep: ['Сохранить и наблюдать', 'Сақтау және бақылау', 'Maintain and monitor'],
  short_period: ['Выберите минимум 7 дней', 'Кемінде 7 күн таңдаңыз', 'Select at least 7 days'],
  fast: ['Высокий', 'Жоғары', 'High'],
  slow: ['Низкий', 'Төмен', 'Low'],
  regular: ['Средний', 'Орташа', 'Average'],
  no_sales: ['Нет продаж', 'Сату жоқ', 'No sales'],
  onlyFlags: ['Только для проверки', 'Тек тексеру үшін', 'Only flagged'],
  onlyAdvice: ['Только рекомендации', 'Тек ұсыныстар', 'Only suggestions'],
  criteria: ['Критерии проверки', 'Тексеру шарттары', 'Review criteria'],
  discountThreshold: ['Скидка от, %', 'Жеңілдік, %-дан', 'Discount from, %'],
  returnThreshold: ['Возврат от, ₸', 'Қайтару, ₸-ден', 'Refund from, ₸'],
  notSpecified: ['Не указано', 'Көрсетілмеген', 'Not specified'],
  writeoffNote: [
    'Стоимость списаний сравнивается с выручкой за тот же период и филиал. Статья и комментарий берутся из документа iiko; при отсутствии причины она не угадывается. Сторно уменьшает итог. Частота — число документов с расходом товара.',
    'Шығару құны сол кезең мен филиал түсімімен салыстырылады. Бап пен пікір iiko құжатынан алынады; жоқ себеп болжанбайды. Сторно қорытындыны азайтады. Жиілік — шығысы бар құжаттар саны.',
    'Write-off cost is compared with revenue for the same period and branch. Accounts and comments come from iiko documents; absent reasons are not inferred. Reversals reduce totals. Frequency counts documents with product outflow.',
  ],
  operationsNote: [
    'Сигналы — повод проверить чек, а не вывод о нарушении. Порог скидки применяется к позициям со скидкой. «Авторизовал» — поле iiko, оно не подтверждает, кто именно назначил скидку. Повторные возвраты: от 3 чеков кассира в филиале за учётный день.',
    'Белгілер — чекті тексеруге себеп, бұзушылық туралы қорытынды емес. Шек жеңілдігі бар позицияларға қолданылады. Рұқсат берген тұлға жеңілдікті кім қойғанын дәлелдемейді. Қайталану: кассирдің филиалда бір есептік күнде 3 чектен бастап қайтаруы.',
    'Signals invite review, not a conclusion of misconduct. Discount thresholds apply to discounted items. The iiko authorizer field does not prove who assigned a discount. Repeated refunds mean 3 or more checks per cashier, branch and accounting day.',
  ],
  assortmentNote: [
    'Показаны товары с продажами в выбранном или предыдущем периоде. Спрос сравнивается внутри филиала и одинаковой единицы. Ориентир на день — средние продажи за календарный день, не готовый план производства. Высокий спрос не доказывает отсутствие товара на полке. Учтите остатки, поставки и день недели. Списания соединяются по ID товара и единице; сырьё с другим ID не относится к готовой выпечке автоматически.',
    'Таңдалған немесе алдыңғы кезеңде сатылған тауарлар көрсетіледі. Сұраныс филиал мен бір өлшем ішінде салыстырылады. Күндік бағдар — орташа сату, дайын өндіріс жоспары емес. Жоғары сұраныс тауардың таусылғанын дәлелдемейді. Қорды, жеткізуді және апта күнін ескеріңіз. Шығару ID мен өлшем бойынша біріктіріледі; басқа ID бар шикізат дайын өнімге автоматты қосылмайды.',
    'Includes products sold in the selected or previous period. Demand is compared within each branch and unit. The daily reference is average sales per calendar day, not a production plan. High demand does not establish a stockout. Account for stock, deliveries and weekdays. Write-offs join by product ID and unit; ingredients with different IDs are not automatically assigned to finished goods.',
  ],
};
export const controlText = (locale: string, key: string) =>
  labels[key]?.[locale === 'kk' ? 1 : locale === 'en' ? 2 : 0] || key;
